#include <iostream>
#include <fstream>
#include <vector>
#include <string>

using namespace std;

uint8_t codificar(char n) {
    switch (n) {
        case 'A': return 0b00;
        case 'C': return 0b01;
        case 'G': return 0b10;
        case 'T': return 0b11;
        default:  return 0b00;
    }
}

char decodificar(uint8_t v) {
    switch (v) {
        case 0b00: return 'A';
        case 0b01: return 'C';
        case 0b10: return 'G';
        case 0b11: return 'T';
        default:   return '?';
    }
}

// Compacta sequência e grava no arquivo "gene.bin"
void compactar_para_arquivo(const string& gene, const string& arquivo) {
    ofstream arq(nome_arquivo, ios::binary);
    if (!arq) {
        cout << "Erro ao criar arquivo!\n";
        return;
    }

    vector<uint8_t> bytes;
    uint8_t atual = 0;
    int contador_bits = 0;

    for (char n : gene) {
        uint8_t codigo = codificar(n);

        atual = (atual << 2) | codigo;
        contador_bits += 2;

        if (contador_bits == 8) {
            bytes.push_back(atual);
            atual = 0;
            contador_bits = 0;
        }
    }

    if (contador_bits > 0) {
        atual = atual << (8 - contador_bits);
        bytes.push_back(atual);
    }

    // salvar quantidade de caracteres (4 bytes)
    uint32_t tamanho = gene.size();
    arq.write(reinterpret_cast<char*>(&tamanho), sizeof(tamanho));

    // salvar bytes compactados
    arq.write(reinterpret_cast<char*>(bytes.data()), bytes.size());

    arq.close();
    cout << "Arquivo gerado com sucesso: " << arquivo << endl;
}

// Lê arquivo compactado e reconstrói o gene
string descompactar_do_arquivo(const string& arquivo) {
    ifstream arq(nome_arquivo, ios::binary);
    if (!arq) {
        cout << "Erro ao abrir arquivo!\n";
        return "";
    }

    uint32_t tamanho = 0;
    arq.read(reinterpret_cast<char*>(&tamanho), sizeof(tamanho));

    vector<uint8_t> bytes((istreambuf_iterator<char>(arq)), istreambuf_iterator<char>());
    arq.close();

    string gene;
    gene.reserve(tamanho);

    int bits_lidos = 0;
    uint8_t atual = 0;

    for (uint8_t b : bytes) {
        for (int i = 6; i >= 0 && gene.size() < tamanho; i -= 2) {
            uint8_t valor = (b >> i) & 0b11;
            gene.push_back(decodificar(valor));
        }
    }

    return gene;
}

int main() {
    string gene = 
"ACCGCGCCTTCTTTTCCTGCGAGGGCCCGGTAGGGACCGAGCGCTTTGATTTAAAGCCTGGTTCTGCTTTGTATGATTTATCTAAAGCAGCCCAATCTAAAGAAACCGGTCCCGGGCACTATAAATTGCCTAACAAGTGCGATTCATTCATGGATCCACAGAACGCCCTGTATTATCAGCCGCGGGTACCCACAGCAGCTCCGACATCCGGAGGAGTGCCGTGGAGTCGCGTAGGCGAGGTAGCTATTTTGAGCTTTGTTGCATTGATTTGCTTTTACCTGCTTTACCTTTGGGTGCTGAGAGACCTTATCTTAGTTCTGAAGGCTCGACAAGGCAGATCCACGGAGGAGCTGATATTTGGTGGACAAGCTGTGGATAGGAGCAACCCTATCCCTAATCTACCTTCACCACCAAGTCAGGGCAATCCCGGGCCATTTGTTCCAGGCACGGGATAAGCAATCAGCCATGTCCACGTCCAAGAGGAAGCGGGGAGATGATTCGAATTGGAATAAGCGGGTGCCTAAGAAGAAGCCATCTTCAGCTGGGCTGAAGAGGGCTGGAAGCAAGGCCGATAGGCCATCCCTCCAAATCCAGACACTCCAGCATGCTGGGACCACCATGATAACTGTCCCATCCGGAGGAGTATGTGACCTCATCAACACCTATGCCCGAGGATCTGACGAGGGCAACCGCCACACCAGCGAGACTCTGACGTACAAGATCGCCGTCGACTACCACTTCGTTGCCGACGCGGCTGCCTGCCGCTACTCCAACACCGGAACCGGTGTAATGTGGCTGGTGTATGACACCACTCCCGGCGGACAAGCTCCGACCCCGCAAACTATATTTGCCTACCCTGACACGCTAAAAGCGTGGCCGGCCACATGGAAAGTGAGCCGGGAGCTGTGTCATCGCTTCGTGGTGAAACGGCGATGGTTGTTCAACATGGAGACCGACGGTCGGATTGGTTCGGATATCCCTCCCTCGAATACAAGTTGGAAGCCTTGCAAGCGCAACATCTACTTCCACAAGTTCACGAGTGGGTTGGGAGTGAGAACGCAGTGGAAGAATGTAACGGACGGAGGAGTTGGTGCCATCCAGAGAGGAGCTCTGTACATGGTCATTGCCCCAGGCAATGGCCTTACTTTTACTGCCCATGGGCAGACCCGTCTGTACTTTAAGAGTGTTGGCAACCAGTAATGAATAAAAACTCCCGTTTTATTATATTTGATGAATGCTGAAAGCTTACATTAATATGTCGTGCGATGGCACGAAAAAACACACGCAAACAATACAGGGGGGTAGTCGGCGGGCGGCTAAGGGTGGTGCTCGGCGGGCAGAACATCGAAAAATCAAGATCTATATGAATTACACTTCCTCCGTAGGAGGAAGCACAGGGGGAGAATACCACTTCTCCCCCGGCGACATAATGTAAATGACGCAGTTTGCCTCGAAATACTCCAGCTGCCCTGGAGTCATTTCCTTCATCCAATCTTCATCCGAGTTGGCGAGGATTATTGTAGGCTTAGACTTCTTCTGCACCTTTTTCTTCTTACCATACTTGGGGTTTACAATGAAATCCCTCTGACAGCCAACTAACTGTTTCCAACAAGGACAGAATTTAAACGGAATATCATCTACGATGTTGTAGATTGCGTCTTCGTTGTATGAAGACCAATCAACATTATTTTGCCAGTAATTATGAACCCCTAGGCTTCTGGCCCAAGTAGATTTTCCGGTTCTTGTTGGGCCGACGATGTAGAGGCTCTGCTTTCTTGATCTTTCATCTGATGACTGGATACAGAATCCATCCATTGGAGGTCAGAAATTGCATCCTCGAGGGTATAACAGGTAGGTTGAAGGAGCATGTAAGCTTCGGGACTAACCTGGAAGATGTTAGGCTGGAGCCAATCGTTGATTGACTCATTACAAAGTAAATCAGGTGAGGAGGGTGGATGAGGATTGGTGAACTCTTCCTGAATCTCAGGAAAAAGCTTATTTGCAGAGTATTCAAAATACTGCAATTTTGTGGACCAATCAAAGGGGAGCTCTTTCTGGATCATGGAGAGGTACTCTTCTTTGGAGGTAGCGTGTGAAATAATGTCTCGCATTATTTCATCTTTAGAAGGCTTTTTTTCCTTTACCTCTGAATCAGATTTTCCTAGGAAGGGGGACTTCCTAGGAATGAAAGTACCTCTCTCAAACACAGCCAGAGGTTCCTTGAGAATGTAATCCCTCACTCTGTTAACTGACTTGGCACTCTGAATATTTGGGTGAAACCCATTTATATCAAAGAACCTTGAGTCAGATATCCTTATCGGCTTCTCTGGCTGAAGCAATGCATGTAAATGCAAACTTCCATCTTTATGTGCCTCTCGGGCACATAGAATATATTTGGGAATCCAACGAACGACGAGCTCCCAGATCATCTGACAGGCGATTTCAGGATTTTCTGGACACTTTGGATAGGTTAGGAACGTGTTAGCGTTCCTGTGTGAGAACTGACGGTTGGATGAGGAGGAGGCCATAGCCGACGACGGAGGTTGAGGCTGAGGGATGGCAGACTGGGAGCTCCAAACTCTATAGTATACCCGTGCGCCTTCGAAATCCGCCGCTCCATTGTCTTATAGTGGTTGTAAATGGGCCGGACCGGGCCGGCCCAGCAGGAAAAGAAGGCGCGCACTAATAT";

    cout << "Gene original:\n" << gene << endl;

    compactar_para_arquivo(gene, "gene.bin");

    string restaurado = descompactar_do_arquivo("gene.bin");

    cout << "\nGene descompactado:\n" << restaurado << endl;

    return 0;
}
